baseurl = "https://jakartaone.org/"
#baseurl = "https://jakartaee.github.io/jakartaone.org/"
DefaultContentLanguage = "en"
title = "JakartaOne Live - September 10, 2019 | Jakarta EE Software | Cloud Native"
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
disableKinds = ["taxonomy", "taxonomyTerm"]
themesDir = "node_modules/"

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "JakartaOne Live is a one day virtual conference for developers and technical business leaders that brings insights into the current state and future of Jakarta EE and related technologies focused on developing cloud-native Java applications."
  subtitle = "JakartaOne Live - September 10, 2019 | Jakarta EE Software | Cloud Native"
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["JakartaOne", "JakartaOne Live", "Jakarta EE software", "Java EE", "cloud", "microservices", "enterprise", "open source", "innovation"]
  logo = "images/jakarta/jakarta-ee-logo.svg"
  styles = "css/styles.css"
  favicon = "images/jakarta/favicon.ico"
  share_img = "images/jakarta/jakarta_ee_400x400.png"
#  gcse = "011805775785170369411:p3ec0igo0qq"
  subtheme = "jakarta"
  header_wrapper_class = "header-default-bg-img"
  js = "js/solstice.js"
# show_events = true
# call_for_action_text = ""
# call_for_action_url = ""
# call_for_action_icon = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "EclipseFdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  
[[menu.main]]
    name = "Plan of the day"
    url = "/#plan-of-the-day"
    weight = 1
    
[[menu.main]]
    name = "Program committee"
    url = "/program-committee/"
    weight = 2

[[menu.main]]
    name = "Attend"
    weight = 3

[[menu.main]]
    name = "Code of Conduct"
    url = "/code-of-conduct/"
    weight = 1
    parent = "Attend"